export {default as Header} from './Header'
export {default as About} from './About'
export {default as Reviews } from './Reviews'
export {default as Services} from './Services'
export {default as Follow} from './Follow'
export {default as Contact} from './Contact'
export {default as Footer} from './Footer.jsx'
// export { default as LocationMap } from './LocationMap.jsx'