import React from 'react'
import Head from 'next/head'
import { Header, About, Reviews, Services, Follow, Contact, Footer } from '../components'
import { getPosts } from '../graphcsm'
import styles from '../styles/Home.module.css'
import { PostCard , PostWidget,Categories } from '../blogComponents'


const Blog = ({posts}) => {
  return (
    <div className='mx-auto px-10 mb-8 '>
      <Head>
        <title>Ngozi website </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 py-40">
        <div className='lg:col-span-8 col-span-1'>

          {posts.map((post, index) => (
            <PostCard key={index} post={post.node} />


          ))}

        </div>

        <div className="lg:col-span-4 col-span-1">

          <div className="lg:sticky relative top-40">
            <PostWidget />
            <Categories />

          </div>
        </div>
      </div>



    </div>
  )
}



export default Blog

export const getStaticProps = async () => {

  const posts = (await getPosts() || [])

  return {

    props: { posts }
  }
}