import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { About, Reviews ,Services ,Follow, Contact ,Footer} from '../components'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ngozi website </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <div className='h-full'>
     <About/>
    <Reviews/>
    <Services/>
    <Follow/>
    <Contact/>
    <Footer/>
     </div>
    </div>
  )
}


